const data = [
  "aclonica",
  "alef",
  "allan",
  "allerta",
  "allerta stencil",
  "amaranth",
  "amatic sc",
  "annie use your telescope",
  "anonymous pro",
  "anton",
  "architects daughter",
  "arimo",
  "artifika",
  "arvo",
  "arya",
  "asap",
  "asset",
  "assistant",
  "astloch",
  "bangers",
  "bentham",
  "bevan",
  "bigshot one",
  "bowlby one",
  "bowlby one sc",
  "brawler",
  "cabin",
  "calligraffitti",
  "candal",
  "cantarell",
  "cantata one",
  "cantora one",
  "caudex",
  "cedarville cursive",
  "cherry cream soda",
  "chewy",
  "coda",
  "coming soon",
  "copse",
  "corben",
  "covered by your grace",
  "crafty girls",
  "crimson text",
  "crushed",
  "cuprum",
  "damion",
  "dancing script",
  "david libre",
  "dawning of a new day",
  "didact gothic",
  "dm serif display",
  "dosis",
  "eb garamond",
  "exo",
  "expletus sans",
  "fontdiner swanky",
  "forum",
  "francois one",
  "frank ruhl libre",
  "geo",
  "georgia",
  "give you glory",
  "goblin one",
  "goudy bookletter 1911",
  "gravitas one",
  "gruppo",
  "hammersmith one",
  "heebo",
  "holtwood one sc",
  "homemade apple",
  "im fell double pica",
  "im fell double pica sc",
  "im fell dw pica",
  "im fell dw pica sc",
  "im fell english",
  "im fell english sc",
  "im fell french canon",
  "im fell french canon sc",
  "im fell great primer",
  "im fell great primer sc",
  "impact",
  "inconsolata",
  "indie flower",
  "irish grover",
  "istok web",
  "josefin sans",
  "josefin slab",
  "judson",
  "jura",
  "just another hand",
  "just me again down here",
  "kameron",
  "kenia",
  "kranky",
  "kreon",
  "kristi",
  "la belle aurore",
  "lato",
  "league script",
  "lekton",
  "limelight",
  "lobster",
  "lobster two",
  "lora",
  "love ya like a sister",
  "loved by the king",
  "luckiest guy",
  "maiden orange",
  "mako",
  "maven pro",
  "meddon",
  "medievalsharp",
  "merriweather",
  "metrophobic",
  "michroma",
  "miltonian",
  "miltonian tattoo",
  "miriam libre",
  "modern antiqua",
  "molengo",
  "monofett",
  "montserrat",
  "mountains of christmas",
  "neucha",
  "neuton",
  "news cycle",
  "nixie one",
  "nobile",
  "nova cut",
  "nova flat",
  "nova mono",
  "nova oval",
  "nova round",
  "nova script",
  "nova slim",
  "nova square",
  "nunito",
  "nunito sans",
  "old standard tt",
  "open sans",
  "open sans condensed",
  "orbitron",
  "oswald",
  "over the rainbow",
  "pacifico",
  "palatino linotype",
  "patrick hand",
  "paytone one",
  "permanent marker",
  "philosopher",
  "play",
  "playfair display",
  "podkova",
  "poppins",
  "pt mono",
  "pt sans",
  "pt sans caption",
  "pt sans narrow",
  "pt serif",
  "pt serif caption",
  "puritan",
  "quattrocento",
  "quattrocento sans",
  "quicksand",
  "radley",
  "raleway",
  "redressed",
  "reenie beanie",
  "roboto",
  "rock salt",
  "rokkitt",
  "rubik",
  "ruslan display",
  "schoolbell",
  "secular one",
  "shadows into light",
  "shanti",
  "sharpsansno1 book",
  "sigmar one",
  "six caps",
  "slackey",
  "smythe",
  "source sans pro",
  "special elite",
  "stardos stencil",
  "sue ellen francisco",
  "suez one",
  "sunshiney",
  "swanky and moo moo",
  "syncopate",
  "tahoma",
  "tangerine",
  "tenor sans",
  "the girl next door",
  "times new roman",
  "tinos",
  "trebuchet ms",
  "ubuntu",
  "ultra",
  "unifrakturcook",
  "unifrakturmaguntia",
  "unkempt",
  "varela",
  "varela round",
  "verdana",
  "vibur",
  "vollkorn",
  "vt323",
  "waiting for the sunrise",
  "wallpoet",
  "walter turncoat",
  "wire one",
  "yanone kaffeesatz",
  "zeyada",
];

module.exports = { data }